### ISSUE TITLE
how to generate meta-model

### ISSUE THREAD

**Issue by TianMing2018** [redis-developer/redis-om-spring-skeleton-app#3]
what do we need to do for generating meta-model automatically? it would be better if you apppend it's steps on `README.md`.
> I didn't find it on search engine

**Comment by TianMing2018** [comment]
it seems that meta-model will generated after you run `mvn spring-boot:run` or `mvn compile` . before that you will get few error tips on your problems tab. sorry about that

**Comment by bwhyman** [comment]
```java
.filter(Person$.FIRST_NAME.eq("BO"))
```
equal to
```java
.filter(new TextTagField<Person, String>(Person.class.getDeclaredField("firstName"), true).eq("BO"))
```

**Comment by bsbodden** [comment]
Correct, the metamodels are meant to simplify the creation of queries with the EntityStreams API. Once Java Lambdas are fully parsable they won't be necessary.
